.MODEL SMALL
.STACK 100H
.DATA
MSG DB 'ENTER A SINGLE PRINTABLE ASCII CHARACTER: $'
MSG2 DB 0DH, 0AH, 'NUMBER$'
MSG3 DB 0DH, 0AH, 'LOWERCASE LETTER$'
MSG4 DB 0DH, 0AH, 'UPPERCASE LETTER$'
MSG5 DB 0DH, 0AH, 'NOT AN ALPHANEUMERIC VALUE$'

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    LEA DX, MSG
    MOV AH, 9
    INT 21H
    
    ;INPUT CHARACTER
    MOV AH, 1
    INT 21H
    
    CMP AL, '0' ; CHAR >= 0?
    JL NOTALPHANEUMERIC ; NO
    CMP AL, '9'
    JLE NUMBER 
    CMP AL, 'A'
    JL NOTALPHANEUMERIC
    CMP AL, 'Z'
    JLE UPPERCASE
    CMP AL, 'a'
    JL NOTALPHANEUMERIC
    CMP AL, 'z'
    JLE LOWERCASE
    JMP NOTALPHANEUMERIC
    
    NUMBER:
    LEA DX, MSG2
    JMP PRINT
    
    LOWERCASE:
    LEA DX, MSG3
    JMP PRINT
    
    UPPERCASE:
    LEA DX, MSG4
    JMP PRINT
    
    NOTALPHANEUMERIC:
    LEA DX, MSG5
    JMP PRINT
    
    PRINT:
    MOV AH, 9
    INT 21H
    ;DOS EXIT
    MOV AH, 4CH
    INT 21H 
    
    MAIN ENDP
END MAIN